### ISSUE TITLE
SST_Task_lock/unlock prototype should be exported in sst_port.h

### ISSUE THREAD

**Issue by prasadghole** [QuantumLeaps/Super-Simple-Tasker#3]
Locking scheduler task experimental functions SST_Task_lock/unlock should be added to sst_port.h for arm as this is giving warnings for implicit function in STM32 IDE.

**Comment by quantum-leaps** [comment]
The prototypes of the scheduler locking functions (`SST_Task_lock()` and `SST_Task_unlock()`) are provided in the `sst.h` header file. Providing them again in the `sst_port.h` header file would be superfluous. I'm not sure why your STM32Cube project gives warnings. Please check your settings.

--MMS

**Comment by prasadghole** [comment]
Checked and fixed the issue. Thank You.
